# Generated by Django 3.1.2 on 2020-10-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='category',
            new_name='room',
        ),
    ]
